
title: My Resume
url: 'Subh94.github.io'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Subhash Kumar
tagline: Software Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: agarwal1994@live.in
phone: 9816479040
website: skumaragarwal.com #do not add http://
linkedin: subhashka
github: Subh94
twitter: '@agarwalsk091'


# Tracker
#analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
